
add_newline = true

format = """
[░▒▓](#A80030)\
[  ](bg:#A80030 fg:#2C2C2C)\
[](bg:#394260 fg:#A80030)\
$directory\
[](fg:#394260 bg:#769ff0)\
$git_branch\
$git_status\
[](fg:#769ff0 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736)\
$fill\
$time\
\n$character"""


[directory]
style = "fg:#e3e5e5 bg:#394260"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#769ff0"
format = '[[ $symbol $branch ](fg:#e3e5e5 bg:#769ff0)]($style)'

[git_status]
style = "bg:#769ff0"
format = '[[($all_status$ahead_behind )](fg:#e3e5e5 bg:#769ff0)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time](fg:#a0a9cb)]($style)'

[fill]
symbol = ' '
